### ISSUE TITLE
Mod configuration not saving (Unleashed Recompiled)

### ISSUE THREAD

**Issue by amso71** [hedge-dev/HedgeModManager#65]
Ever since I have updated to beta 4, the mod configuration fails to be saved. 

[HedgeModManager.log](https://github.com/user-attachments/files/19304684/HedgeModManager.log)

**Comment by thesupersonic16** [comment]
Issue should already be fixed in the [dev builds](https://github.com/hedge-dev/HedgeModManager/actions/runs/13893211206). Please make sure the issue does not occur on the dev builds.

**Comment by amso71** [comment]
Issue 

[HedgeModManager.log](https://github.com/user-attachments/files/19304855/HedgeModManager.log)

still occurs on the latest dev build.

**Comment by thesupersonic16** [comment]
I should have looked at the log first

```
System.IO.IOException: Read-only file system : '/run/media/deck/105e181d-1dde-4b86-9a9e-590006faf89b/steamapps/common/Sonic Unleashed/mods/ModsDB.ini'
```
Something is causing the mod files to become read-only. Can you check if the solution at #39 helps?

Right now the cause is unknown, any extra information of what you have done might help with figuring it out.

**Comment by amso71** [comment]
Sorry for the wait but yes, using flatseal and changing the permissions works. Configurations can be saved again

**Comment by thesupersonic16** [comment]
What permission was set before?
